<?php
    $link_profil = Mage::getUrl('customer/account');
?>
<div class="breadcrumbs">
    <ul>
        <li>
            <strong><span class="root txt"><?php echo  $this->__('Espace Client') ?></span></strong>
            <span> <i class="icon-right-open-big"></i> </span>
        </li>
        <li class="cms_page" >
            <span class="txt"><?php echo $this->__('Mes applications') ?></span>
        </li>
    </ul>
</div>
