<?php 
$keys_menu = explode(',', $this->getMenu()); 
?>

<div class="block-bottom-links">
    <div class="container">
        <div class="row">
        <?php foreach($keys_menu as $key_menu) : ?>
            <?php if ($key_menu != null): ?>
            <div class="col-sm-6 col-menu">
                <?php $menu = Mage::getModel('fluidmenu/fluidmenu')->load($key_menu, 'key_menu') ?>
                <div class="content">
                    <h3><?php echo $menu->getName();?></h3>
                    <?php $menuItems = $this->getMenuItems($key_menu); ?>
                    <?php if (count($menuItems) > 0): ?>                        
                        <ul>
                          <?php foreach ($menuItems as $_menuItem): ?>
                                    <li <?php echo $_menuItem->getClassHtml(); ?> >
                                              <a href="<?php echo $_menuItem->getRealUrl() ?>"  <?php echo $_menuItem->getProprerty(); ?> >
                                                  <span><?php echo $_menuItem->getName() ?></span>
                                              </a>
                                              <?php echo $this->getSubMenuBlock($_menuItem)->toHtml(); ?>
                                    </li>
                          <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            </div>
        <?php endforeach;?>
        </div>
    </div>
</div>