<?php 
$limit = $this->getLimit();
$key_menu = $this->getMenu(); ?>
<?php if ($key_menu != null): ?>
	  <?php $menu = Mage::getModel('fluidmenu/fluidmenu')->load($key_menu, 'key_menu'); ?>
	  <?php $menuItems = $this->getMenuItems($key_menu, $limit); ?>
	  <?php if (count($menuItems) > 0): ?>
				<div class="holder">
						<div class="ht3" >Les garanties <strong class="text-brazeco">Brazeco</strong></div>
					    <ul>
						      <?php foreach ($menuItems as $_menuItem): ?>
							        <li>
							        	<a href="<?php echo $_menuItem->getRealUrl() ?>"  <?php echo $_menuItem->getProprerty(); ?> >
									         <span class="ico" >icon</span>
									         <strong><?php echo $_menuItem->getName() ?></strong>
									     </a>
							        </li>
						      <?php endforeach; ?>
					    </ul>
					    <?php 
					    	// Block note
					    	$block = $this->getLayout()->createBlock('cms/block')->setBlockId('note-garantie')->toHtml(); 
					    	if(!empty($block)){ 
					    		echo "<div class='note' >".$block."</div>"; 
					    	} 
					    ?>
				  </div>
	  <?php endif; ?>
<?php endif; ?>