<?php $key_menu = $this->getMenu(); ?>
<?php if ($key_menu != null): ?>
	  <?php $menu = Mage::getModel('fluidmenu/fluidmenu')->load($key_menu, 'key_menu'); ?>
	  <?php $menuItems = $this->getMenuItems($key_menu); ?>
	  <?php if (count($menuItems) > 0): ?>
		  <nav class="add-nav">
		  		<div>
		  			<ul>		  		
				      <?php foreach ($menuItems as $_menuItem): ?>
				      		<li>
					        	<a href="<?php echo $_menuItem->getRealUrl() ?>"  <?php echo $_menuItem->getProprerty(); ?>>
					        		<span <?php echo ($_menuItem->isActive()) ? "class='active'" : ""; ?> >
					        			<?php echo $_menuItem->getName() ?>
					        			<span class="ico" >ico</span>
					        		</span>					        		
					        	</a>
							</li>
				      <?php endforeach; ?>
				      </ul>
			      </div>				 
			</nav>
	  <?php endif; ?>
<?php endif; ?>