
<?php if ($this->getMenu() != null): ?>
	  <?php $menuItems = $this->getMenuItems( $this->getMenu() ); ?>
	  <?php if (count($menuItems) > 0): ?>                        
                        <ul class="nav navbar-nav" <?php echo trim($this->getHtmlId()) ? 'id="'.$this->getHtmlId().'"' : '';?>>
                                      <?php foreach ($menuItems as $_menuItem): ?>
                                                <li <?php echo $_menuItem->getClassHtml(); ?> >
                                                          <a href="<?php echo $_menuItem->getRealUrl() ?>"  <?php echo $_menuItem->getProprerty(); ?> >
                                                              <span><?php echo $_menuItem->getName() ?></span>
                                                          </a>
                                                          <?php echo $this->getSubMenuBlock($_menuItem)->toHtml(); ?>
                                                </li>
                                      <?php endforeach; ?>
                        </ul>
	  <?php endif; ?>
<?php endif; ?>