<div id="page_cms_awards">

    <div class="page-cms-title-wrapper">
        <h3 class="page-cms-title"><?php echo $this->__('Le système audio<br/>le plus récompensé de l\'histoire') ?></h3>
        <div class="awards-count-wrapper">
            <div class="count-wrapper">37</div>
            <div class="awards-title">awards</div>
        </div>
    </div>

    <div class="container">
        <div class="row awards-container">

            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-1.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-2.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-3.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-4.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-5.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-6.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-7.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-8.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-9.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-10.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-11.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-12.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-13.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-14.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-15.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-16.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-17.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-18.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-19.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>
            <div class="col-sm-3 award-wrapper">
                <div class="table-cell-wrapper">
                    <div class="image-wrapper">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'wysiwyg/Devialet/Phantom/logo-20.png'; ?>" />
                    </div>
                </div>
                <div class="awards-label">
                    <?php echo $this->__('Nomination for design awards') ?>
                </div>
            </div>

        </div>
    </div>

    <div class="cms-page-bottom">
        <div class="bottom-content">
            Convertissez-vous dès maintenant à Devialet, le plus grand
            <br/>
            succès du son haut-de-gamme, le plus primé,
            <br/>
            le plus vendu dans le monde, les meilleures performances
            <br/>
            mesurées grâce à la technologie exclusive ADH®
        </div>
    </div>
</div>