<div id="page_cms_cyber">

    <div class="page-cms-title-wrapper">
        <h3 class="page-cms-title"><?php echo $this->__('Un son différent ,<br/>le meilleur son au monde') ?></h3>
    </div>

    <div class="page-cms-content-wrapper float-wrapper">

        <div class="content-left">

            <div class="text-wrapper">
                <p>
                    Pour la première fois, Phantom émet un son
                    <br/>
                    ultra-dense à impact physique, avec une puissance,
                    <br/>
                    netteté et clarté jamais atteinte.
                </p>
                <p>
                    Même à des niveaux de volume très élevés, le son de
                    <br/>
                    Phantom ne connaît aucune distorsion. Et si votre
                    <br/>
                    musique comporte des silences, Phantom n’émet
                    <br/>
                    absolument aucun souffle.
                </p>
                <p>
                    Pour arriver à cette performance inédite,
                    <br/>
                    il a fallu inventer un système totalement
                    <br/>
                    cybernétique intégrant trois inventions majeures
                    <br/>
                    d’ingénierie.
                </p>

            </div>

            <div class="tab-wrapper">
                <div class="tab-label-wrapper"><?php echo $this->__('En termes techniques cela se traduit') ?></div>
                <table>
                    <thead>
                        <tr>
                            <th><?php echo $this->__('Phantom') ?></th>
                            <th><?php echo $this->__('Silver phantom') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <div>750 w</div>
                                <div>99 db SPL</div>
                            </td>
                            <td>
                                <div>3000 w</div>
                                <div>105 db SPL</div>
                            </td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2">BANDE PASSANTE DE 16HZ à 20KHZ</td>
                        </tr>
                    </tfoot>
                </table>
                <div></div>
            </div>

            <div class="bottom-content float-wrapper">
                <div class="stat-wrapper">
                    <div class="stat-value">0</div>
                    <div class="stat-label"><?php echo $this->__('Distorsion') ?></div>
                </div>
                <div class="stat-wrapper">
                    <div class="stat-value">0</div>
                    <div class="stat-label"><?php echo $this->__('Souffle') ?></div>
                </div>
                <div class="stat-wrapper">
                    <div class="stat-value">0</div>
                    <div class="stat-label"><?php echo $this->__('Saturation') ?></div>
                </div>
            </div>

        </div>

        <div class="content-right">
            <div class="image-wrapper">
                <img src="<?php echo $this->getSkinUrl('images/cyber.png') ?>"/>
            </div>
        </div>

    </div>

</div>