<?php $key_menu = $this->getMenu(); ?>
<?php if ($key_menu != null): ?>
    <?php $menuItems = $this->getMenuItems($key_menu); ?>
    <?php if (count($menuItems) > 0): ?>
        <ul <?php echo trim($this->getHtmlId()) ? 'id="'.$this->getHtmlId().'"' : '';?> class="float-wrapper">
            <?php foreach ($menuItems as $_menuItem): ?>
                <li <?php echo $_menuItem->getClassHtml(); ?>>
                    <a href="<?php echo $_menuItem->getRealUrl() ?>"  <?php echo $_menuItem->getProprerty(); ?> >
                        <?php echo $_menuItem->getName() ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<?php endif; ?>

