<div id="phantom_menu">
    <?php $key_menu = $this->getMenu(); ?>
    <?php if ($key_menu != null): ?>
        <?php $menuItems = $this->getMenuItems($key_menu); ?>
        <?php if (count($menuItems) > 0): ?>
            <ul class="nav nav-pills nav-phantom"  >
                <?php foreach ($menuItems as $_menuItem): ?>
                    <li <?php echo $_menuItem->getClassHtml(); ?> >
                        <a href="<?php echo $_menuItem->getRealUrl() ?>"  class="btn btn-primary btn-lg" role="button" >
                            <?php echo $_menuItem->getName() ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endif; ?>
</div>
