<div class="buttons-set">
    <p class="back-link"><a class="b-white" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <p class="register-product-link"><a class="b-white" href="<?php echo Mage::getUrl('productregistration/productregistration/registerProduct/') ?>"><?php echo $this->__('Register a product') ?></a></p>
</div>