<?php
/**
 * Paybox Epayment module for Magento
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * available at : http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Paybox_Epayment
 * @copyright  Copyright (c) 2013-2014 Paybox
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$cards = $this->getCreditCards();
$current = $this->getInfoData('cc_type');
$hasCctypes = $this->getMethod()->getHasCctypes();
$methodCode = $this->getMethod()->getCode();

?> 
    <?php
    // No card selection
    if (!$hasCctypes):
        ?>
        <p><?php echo $this->__('After confirmation of your order you will be redirected to the payment page.'); ?></p>
        <?php
    else:
        ?>
        <?php
        foreach ($cards as $code => $card):
            $label = $this->__($card['label']);
            $image = $this->getSkinUrl($card['image']);
            $id = $this->htmlEscape('cc_type_' . $methodCode . '_' . preg_replace('#[^a-zA-Z0-9]#', '', strtolower($code)));
            $selected = ($current == $code ? ' selected="selected"' : '');
            $value = $this->htmlEscape($code);
            ?>
                <span class="pbxep-payment-card">
                    <label for="<?php echo $id; ?>">
                        <img src="<?php echo $image; ?>" alt="<?php echo $label; ?>" title="<?php echo $label; ?>" />
                    </label>
                    <input type="radio" name="payment[cc_type]" 
                           onclick="jQuery('#p_method_<?php echo $methodCode;?>').prop('checked',true)" 
                           value="<?php echo $value; ?>"  id="<?php echo $id; ?>"<?php echo $selected; ?> /> 
                </span>
            <?php endforeach; ?>
      
    <?php endif; ?> 

